// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var loc;
    loc = (function() {
      function loc() {}

      loc.run = function() {
        return console.log(hash);
      };

      return loc;

    })();
    return loc;
  });

}).call(this);
