// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var main;
    main = (function() {
      function main() {}

      main.run = function() {};

      return main;

    })();
    return main;
  });

}).call(this);
