// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var main;
    main = (function() {
      function main() {}

      main.run = function() {
        console.log(location.host);
        console.log(location.hash);
        console.log(navigator.appCodeName);
        console.log(navigator.appName);
        return console.log(navigator.appVersion);
      };

      return main;

    })();
    return main;
  });

}).call(this);
