// Generated by CoffeeScript 1.6.3
(function() {
  var PageSnapshot, pageSnapshot;

  PageSnapshot = require('./page_snapshot');

  pageSnapshot = new PageSnapshot();

  pageSnapshot.snapshot('http://www.baidu.com', __dirname + '/baidu.png');

}).call(this);
