// Generated by CoffeeScript 1.6.3
(function() {
  var Job, JobManager, callback, fs, guid, i, job, _i;

  guid = require('./guid');

  fs = require('fs');

  Job = require('./job');

  JobManager = require('./job-manager');

  callback = function(status, id) {
    if (status === 'success') {

    } else {

    }
    return console.log(new Date());
  };

  fs.writeFile("./time.txt", new Date());

  console.log(new Date());

  setTimeout((function() {
    return process.kill("SIGINT");
  }), 3000);

  for (i = _i = 0; _i < 500; i = ++_i) {
    job = new Job('http://www.baidu.com', __dirname + ("/snapshot/baidu" + i + ".png"), callback);
    JobManager.push(job);
  }

}).call(this);
