// Generated by CoffeeScript 1.6.3
(function() {
  var JobManager, PageSnapshot, guid;

  guid = require('./guid');

  PageSnapshot = require('./page-snapshot');

  JobManager = (function() {
    function JobManager() {}

    JobManager.freeNum = 2;

    JobManager.pool = [];

    JobManager.workerJobMap = {};

    JobManager.push = function(job) {
      return JobManager.pool.push(job);
    };

    JobManager.checker = function() {
      var jobs;
      if (JobManager.freeNum > 0 && JobManager.pool.length > 0) {
        if (JobManager.pool.length > 100) {
          jobs = JobManager.pool.splice(0, 100);
        } else {
          jobs = JobManager.pool;
          JobManager.pool = [];
        }
        JobManager.doJob(jobs);
        return JobManager.checker();
      } else {
        return setTimeout(JobManager.checker, 200);
      }
    };

    JobManager.doJob = function(jobs) {
      var pageSnapshot;
      JobManager.freeNum -= 1;
      jobs = JSON.stringify({
        jobList: jobs
      });
      pageSnapshot = new PageSnapshot();
      return pageSnapshot.snapshot(jobs, JobManager.callback);
    };

    JobManager.callback = function(status, workerId) {
      return JobManager.freeNum += 1;
    };

    JobManager.init = function() {
      return this.checker();
    };

    return JobManager;

  }).call(this);

  JobManager.init();

  module.exports = JobManager;

}).call(this);
