// Generated by CoffeeScript 1.6.3
(function() {
  var PageSnapshot, process,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  process = require('child_process');

  PageSnapshot = (function() {
    function PageSnapshot() {
      this.snapshot = __bind(this.snapshot, this);
      this.onTimeout = __bind(this.onTimeout, this);
      this.onExit = __bind(this.onExit, this);
      this.error = false;
    }

    PageSnapshot.prototype.onExit = function(code) {
      console.log(code);
      if (code === null) {
        console.log('snapshot url: ' + this.url + ' timeout.');
      } else if (code === 0) {
        console.log('snapshot url: ' + this.url + ' success.');
      } else {
        console.log('unknown error.');
      }
      this.endTime = new Date();
      return console.log('Spend ' + (this.endTime - this.startTime) + 'ms.');
    };

    PageSnapshot.prototype.onTimeout = function() {
      return this.worker.kill('SIGINT');
    };

    PageSnapshot.prototype.snapshot = function(url, path) {
      this.url = url;
      this.path = path;
      this.startTime = new Date();
      this.worker = process.spawn('phantomjs', ['--disk-cache=true', __dirname + '/phantomjs_script/snapshot.js', url, path]);
      return this.worker.on('exit', this.onExit);
    };

    return PageSnapshot;

  })();

  module.exports = PageSnapshot;

}).call(this);
