// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var AdRemark, Spine, _ref;
    Spine = require('spine');
    AdRemark = (function(_super) {
      __extends(AdRemark, _super);

      function AdRemark() {
        _ref = AdRemark.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      AdRemark.configure('AdRemark', 'id', 'domains', 'remark');

      AdRemark.extend(Spine.Model.Ajax);

      AdRemark.include(Spine.Model.Ajax);

      return AdRemark;

    })(Spine.Model);
    return AdRemark;
  });

}).call(this);
