// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var Domain, Spine, domain, domains, i, _i, _ref, _ref1;
    Spine = require('spine');
    domains = require('../../campaign/domains/' + G.LANG);
    Domain = (function(_super) {
      __extends(Domain, _super);

      function Domain() {
        _ref = Domain.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Domain.configure("Domain", "id", "name");

      return Domain;

    })(Spine.Model);
    for (i = _i = 0, _ref1 = domains.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
      domain = new Domain({
        id: i + 1,
        name: domains[i]
      });
      domain.save();
    }
    return Domain;
  });

}).call(this);
