// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var $, Role, RoleList, Spine, langResourceCommon, langResourceRole, rfl, _ref;
    $ = require('jquery');
    Spine = require('spine');
    rfl = require('rfl');
    langResourceCommon = require('lang/{{G.LANG}}/common');
    langResourceRole = require('lang/{{G.LANG}}/role');
    Role = require('../models/role');
    RoleList = (function(_super) {
      __extends(RoleList, _super);

      function RoleList() {
        this.del = __bind(this.del, this);
        this.render = __bind(this.render, this);
        this.ajaxError = __bind(this.ajaxError, this);
        _ref = RoleList.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      RoleList.prototype.events = {
        'click [data-del-btn]': 'del'
      };

      RoleList.prototype.template = require('../views/role-list.tpl.html');

      RoleList.prototype.init = function() {
        Role.on('refresh', this.render);
        Role.on('ajaxError ajaxBizError', this.ajaxError);
        return Role.ajaxFetch();
      };

      RoleList.prototype.ajaxError = function(record, type, res, status, xhr) {
        if (!rfl.ajax.dealCommonCode(res.code)) {
          return rfl.alerts.show(res.message || langResourceCommon.msg.serverBusy, 'error');
        }
      };

      RoleList.prototype.render = function() {
        return this.html(this.template.render({
          roles: Role.all()
        }));
      };

      RoleList.prototype.del = function(evt) {
        var id, role;
        id = $(evt.target).closest('tr').data('id');
        role = Role.find(id);
        return rfl.alerts.confirm(rfl.util.formatMsg(langResourceRole.msg.delRoleConfirm, [role.name]), function() {
          return role.ajaxDestroy({
            done: function(res) {
              rfl.alerts.show(res.message, 'success');
              return Role.ajaxFetch();
            }
          });
        }, {
          makeSure: true
        });
      };

      return RoleList;

    })(Spine.Controller);
    return RoleList;
  });

}).call(this);
