// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var Role, Spine, _ref;
    Spine = require('spine');
    Role = (function(_super) {
      __extends(Role, _super);

      function Role() {
        _ref = Role.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Role.configure('Role', 'name', 'description', 'superRole', 'permissionIds');

      Role.extend(Spine.Model.Ajax);

      Role.include(Spine.Model.Ajax);

      return Role;

    })(Spine.Model);
    return Role;
  });

}).call(this);
